# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jemoji]

# Setup
title:            Lucas Lehnert
tagline:          "Personal Website"
description:      "Postdoctoral Researcher<br/>FAIR at Meta"
url:              http://lucaslehnert.github.io
baseurl:          /

paginate:         3

linkedin: https://www.linkedin.com/in/lucaslehnert
github: https://github.com/lucaslehnert
